routes/web.php
    Route::any('product/single/{nom}', 'Product@single');
    Route::any('product', 'Product@index');
    Route::post('/product/export', 'Product@exportCsv')->name('exportProduct');
    Route::any('product/status/{product_id}', 'Product@changeStatus');
    Route::any('RemoveProductImate/{ID}/{Index}', 'Product@RemoveImage');
    Route::any('product/print/{product_id}', 'Product@print');
    Route::any('product/delete/{product_id}', 'Product@delete');
    Route::any('buyer-product/{user_id}', 'BuyerProduct@index');
    Route::post('buyer-product/{user_id}/export', 'BuyerProduct@exportCsv')->name('exportBuyerProduct');
    Route::any('product/Copy/{product_id}', 'Product@CopyProduct');

    // Location
    Route::any('country/{nom?}', 'LocationController@country');
    Route::any('state/{nom?}', 'LocationController@state');
    Route::any('city/{nom?}', 'LocationController@city');
    Route::post('/country/export/csv', 'LocationController@countryexportCsv')->name('exportCountry');
    Route::post('/state/export/csv', 'LocationController@stateexportCsv')->name('exportState');
    Route::post('/city/export/csv', 'LocationController@cityexportCsv')->name('exportCity');

    Route::any('shipping-line/{nom?}', 'ShippingLine@index');
    Route::post('/shipping-line/export/csv', 'ShippingLine@exportCsv')->name('exportShippingLine');
    Route::any('finish/{nom?}', 'Finish@index');
    Route::post('/finish/export/csv', 'Finish@finishExportCsv')->name('exportFinish');

    Route::any('Material/{nom?}', 'MaterialController@index');
    Route::any('MaterialType/{nom?}', 'MaterialType@index');
    Route::post('/Material/export/csv', 'MaterialController@materialexportCsv')->name('exportMaterial');
    Route::post('/MaterialType/export/csv', 'MaterialType@materialTypeExportCsv')->name('exportMaterialType');


    Route::any('forwarder/{nom?}', 'Forwarder@index');
    Route::post('/forwarder/export/csv', 'Forwarder@exportCsv')->name('exportForwarder');
    Route::any('port/{nom?}', 'Port@index');
    Route::post('/port/export/csv', 'Port@portexportCsv')->name('exportPort');
    Route::any('unit/{nom?}', 'Unit@index');
    Route::post('/unit/export/csv', 'Unit@exportCsv')->name('exportUnit');
    Route::get('view-detail/{nom}', 'Viewdetail@index');

    Route::any('enquiry/{nom?}', 'Enquiry@index');
    Route::any('quote/add/{enq_id?}/{id?}', 'Quote@add');
    Route::any('quote/new-add', 'Quote@NewAdd');
    Route::any('quote/send/{id}', 'Quote@send');
    Route::any('quote', 'Quote@index');
    Route::any('quote/info/{id?}', 'Quote@single');
    Route::any('quote/revisions/{id?}', 'Quote@revisions');

    // Quote Ajax
    Route::post('get-quote-products', 'Quote@get_quote_products')->name('ajax.quote.products');
    Route::post('purchase-order/cart', 'PurchaseOrderController@cartStore')->name('purchase-order.cart.store');

    // Vendor Part
    Route::any('quote/send/{id}', 'Send_vendor@index');
    Route::any('assign-vendor/{id}', 'Send_vendor@send');

    Route::any('vquote', 'Vquote@index');
    Route::any('vquote/info/{id}', 'Vquote@single');
    Route::any('vquote/add/{enq_id}/{id?}', 'Vquote@add');
    Route::any('vquotestatus', 'Vquote@enquiry_status');
    Route::any('vquotestatus/{enq_id}', 'Vquote@enquiry_quote');

    Route::any('vendor-enquiry', 'Vendor_enquiry@index');
    Route::any('vendor-quote', 'Vendor_quote@index');
    Route::any('vendor-quote/info/{$id}', 'Vendor_quote@single');

    //   Invoice
    Route::any('performa-invoice/add/{quote_id}/{pi_id?}', 'PI_Controller@add');
    Route::any('performa-invoice/edit/{quote_id}/{pi_id?}', 'PI_Controller@update');
    Route::get('performa-invoice', 'PI_Controller@index');
    Route::get('performa-invoice/print/{pi_id}', 'PI_Controller@print');
    Route::get('ConfirmPI/{ID}/{Date}/{DP}', 'PI_Controller@ConfirmPI');
    Route::post('/performa-invoice/export', 'PI_Controller@exportCsv')->name('exportPi');


    Route::get('commercial-invoice/print/{pi_id}', 'PurchaseOrderController@CIPrint');
    Route::get('booking-commercial-invoice/print/{pi_id}', 'PurchaseOrderController@BookingCIPrint');


    Route::get('purchase-order/view-invoice/{pi_id}', 'PurchaseOrderController@ViewVendorInvoice');
    Route::any('purchase-order/choose-buyer', 'PurchaseOrderController@ChooseBuyer');
    Route::any('purchase-order/create-invoice', 'PurchaseOrderController@CreateVendorInvoice');
    Route::any('purchase-order/create-final-invoice', 'PurchaseOrderController@CreateFinalVendorInvoice');

    Route::get('purchase-order/view-invoice/{pi_id}', 'PurchaseOrderController@ViewVendorInvoice');

    Route::any('create-ghp-invoice/{po_id}', 'Pinvoice@CreateGHPInvoice');

    Route::get('purchase-order', 'PurchaseOrderController@index')->name('purchase-order.index');
    Route::post('/purchase-order/export', 'PurchaseOrderController@exportCsv')->name('exportPo');
    Route::get('purchase-order/transfer/{purchase_order}', 'PurchaseOrderController@transfer')->name('po.transfer');
    Route::post('purchase-order/transfer/{purchase_order}', 'PurchaseOrderController@storeTransfer')->name('po.transfer.store');



    Route::get('vendor-booking-invoice', 'PurchaseOrderController@AllVendorBookingInvoice');
    Route::get('vendor-invoice', 'PurchaseOrderController@AllVendorInvoice');
    Route::post('vendor-invoice-export', 'PurchaseOrderController@AllVendorInvoiceCsv')->name('CommercialInvoiceExport');

    Route::any('purchase-order/add/{enq_id}/{quto_id}', 'PO_Controller@add');
    Route::get('purchase-order/print/{pi_id}', 'PO_Controller@print');
    Route::get('purchase-order/copy/{pi_id}', 'PO_Controller@copy');
    Route::get('purchase-order/edit/{pi_id}', 'PO_Controller@edit');

    Route::get('purchase-order-sample/print/{pi_id}', 'PO_Controller_Sample@print');


    Route::post('purchase-order/edit-save', 'PO_Controller@saveedit');

    // test print offer 
    Route::any('offer/print/{offer}', 'OfferController@print')->name('offer.print');


    Route::any('vendor-enquiry', 'Vendor_enquiry@index');
    Route::any('vendor_quote/add/{num}', 'Vendor_quote@add');

    Route::any('user/add/buyer/{id?}', 'User@add_buyer');
    Route::any('user/change_status/{role}/{id?}', 'User@change_status');
    Route::any('user/add/employee/{id?}', 'User@add_employee');
    // Route::any('user/buyer', 'User@index');

    Route::any('user/add/{role}/{id?}', 'User@add');
    Route::any('user/vendor', 'User@vendor');
    Route::any('user/{role}', 'User@index');

    Route::any('user/profile/buyer', 'User@BuyerProfile');

    Route::any('ajax/user_login', 'Ajax@user_login');
    Route::any('ajax/get_states/{ID}', 'Ajax@get_states');
    Route::any('ajax/{action}', 'Ajax@index');
    Route::get('ajax/approve_qpro/{qid}/{pid}', 'Ajax@approve_qpro');
    Route::get('ajax/approve_vqpro/{qid}/{pid}', 'Ajax@approve_vqpro');
    Route::any('ajax/add_to_cart/{sess_name}', 'Ajax@add_to_cart');
    Route::any('ajax/update_cart/{sess_name}', 'Ajax@update_cart');
    Route::any('ajax/remove_cart/{sess_name}', 'Ajax@remove_cart');


    Route::get('ghp-invoice-list', 'Pinvoice@index');
    Route::get('ghp-commercial-invoice/print/{ID}', 'Pinvoice@GhpCommercialInvoicePrint');
    Route::get('packing-list/print/{ID}', 'Pinvoice@GhpPackingListPrint');


    Route::get('view-logistic', 'Logistic@ViewAll');
    Route::post('view-logistic/export', 'Logistic@exportCsv')->name('exportLogistic');
    Route::any('Logistics/add/{id?}', 'Logistic@Add');
    Route::get("LoadPIData/{ID}", 'Logistic@LoadPI');
    Route::get("LoadPOData/{ID}", 'Logistic@LoadPO');
    Route::get("LoadOtherData/{ID}", 'Logistic@LoadOther');

    Route::get("GetBuyerPrices/{ID}", 'Ajax@GetPrevQuotePrice');
    Route::get("LoadBuyerPO/{ID}", 'PurchaseOrderController@LoadBuyerPO');



    Route::get("inventory", 'Inventory@ViewAll');
    Route::post('/inventory/export', 'Inventory@exportCsv')->name('exportInventory');

    Route::get("qc-schedule", 'QC@Schedule');
    Route::get("qc-new", 'QC@New');
    Route::get("qc_inspection_po", 'QC@Inspectoin');
    Route::get("qc-checklist", 'QC@Checklist');
    Route::get("qc-image", 'QC@Image');
    Route::get("qc-final", 'QC@Final');


    Route::get("Samplesheet", 'DashboardController@Samplesheet');
    Route::get("Samplesheet/Delete/{ID}", 'DashboardController@DeleteSheet');
    Route::post("SaveFiles", 'DashboardController@SaveFiles');


    Route::get("buyer_product/add", 'Buyer_products@index');
    Route::post("buyer_product/get_products", 'Buyer_products@get_products')->name('get_products');
    Route::post("buyer_product/upload_buyer_products", 'Buyer_products@upload_buyer_products')->name('upload_buyer_products');
    Route::get("buyer_product/view", 'Buyer_products@view_buyer_products')->name('view_buyer_products');
    Route::post("buyer_product/get_buyer_products", 'Buyer_products@get_buyer_products')->name('get_buyer_products');

    Route::get("vendor_grid_reports", 'Grid_reports@vendor')->name('vendor_grid_reports');
    Route::post("vendor_grid/products", 'Grid_reports@grid_products')->name('vendor_grid_products');
    Route::post("get_excel_products", 'Buyer_products@get_excel_products')->name('get_excel_products');

    Route::get("buyer_grid_reports", 'Grid_reports@buyer')->name('buyer_grid_reports');
    Route::post("buyer_grid/products", 'Grid_reports@buyer_grid_products')->name('buyer_grid_products');
    Route::post("get_excel_products", 'Grid_reports@get_buyer_excel_products')->name('get_buyer_excel_products');
    Route::get('logs', 'LogController@index')->name('logs');
    // Update Grid Remarks
    Route::post("update_grid", 'Grid_reports@update_grid')->name('updateGrid');
    Route::post("update_vendor_grid", 'Grid_reports@update_vendor_grid')->name('updateVenderGrid');

    // Export to excel
    Route::post('/vendor/export_grid_list', 'Grid_reports@vendor_export')->name('export_vendor_grid_list');
    Route::resources([
        'role' => 'RoleController',

app/Models/Offer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{
    public function offer_products()
    {
        return $this->belongsToMany('App\Models\Product', 'offer_products', 'offer_id', 'product_id')->withPivot('qty', 'margin', 'price', 'moq', 'remarks');
    }
}

app/Http/Controllers/OfferController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Routing\Controller;
use App\Models\Offer;
use App\Models\Cart;
use App\Models\Product;
use Illuminate\Http\Request;

class OfferController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $offers = Offer::latest()->paginate(10);
        return view('frontend.inc.offer.index', compact('offers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::get();
        return view('frontend.inc.offer.create', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $offer = new Offer();
        $offer->buyer_name = $request->buyer_name;
        $offer->refered_by = $request->refered_by;
        $offer->price_validity = $request->price_validity;
        $offer->lead_time = $request->lead_time;
        $offer->remarks = $request->remarks;
        $offer->terms = $request->terms;
        $offer->save();

        $carts = Cart::with('product')->where('type', 'offer')->get();
        $offerProducts = [];
        foreach ($carts as $c) {
            $offerProducts[$c->product_id] = [
                'qty'   => $c->qty,
                'margin' => $c->margin,
                'remarks'   => $c->remarks,
                'price' => round($c->product->product_mrp + $c->product->product_mrp * $c->margin / 100, 2),
                'moq'       => $c->moq
            ];
        }
        $offer->offer_products()->sync($offerProducts);

        Cart::where('type', 'offer')->delete();

        return redirect(route('offer.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function show(Offer $offer)
    {
        // dd($offer->offer_products);
        return view('frontend.inc.offer.show', compact('offer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function edit(Offer $offer)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Offer $offer)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Offer $offer)
    {
        //
    }

    public function print(Offer $offer)
    {
        $data       = compact('offer');

        return view('frontend.inc.offer.print', $data);
    }
}

resources/views/frontend/inc/offer/edit.blade.php
@extends('frontend.layouts.app')

@section('main_section')
    <section class="page-header mb-3">
        <div class="container-fluid">
            <div class="clearfix">
                <div>
                    <h1>Edit Role</h1>
                    <ul class="breadcrumbs clearfix">
                        <li><a href="">Dashboard</a></li>
                        <li class="active">Edit Role</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    {{ Form::open(['url' => route('role.update', [$role->id]), 'method' => 'put', 'class' => 'container-fluid']) }}
    <div class="card mt-5">
        <h3 class="card-title">Edit Role</h3>
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col-sm-3"><label>Name</label></div>
                    <div class="col-sm-9">
                        <div class="form-group">
                            {{ Form::text('name', null, ['placeholder' => 'Enter Name', 'class' => 'form-control', 'required' => 'required']) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <h3 class="card-title">Permissions</h3>
        @foreach ($permissions as $p)
        <div class="checkbox">
            <label>
                <!-- <input name="permission[]" type="checkbox" value="{{ $p }}"> -->
                {{ Form::checkbox('permission[]', $p) }}
                {{ $p }}
            </label>
        </div>
        @endforeach
        <div>
            <button type="submit" class="btn btn-primary px-5">Update</button>
        </div>
    </div>
    {{ Form::close() }}
@endsection

resources/views/frontend/inc/offer/index.blade.php
@extends('frontend.layouts.app')

@section('main_section')
    <section class="page-header mb-3">
        <div class="container-fluid">
            <div class="float-right">
                <a href="{{ route('offer.create') }}" class="btn btn-default"> <i class="icon-plus"></i> Add Offer</a>
            </div>
            <div class="clearfix">
                <div >
                    <h1>Offer</h1>
                    <ul class="breadcrumbs clearfix">
                        <li><a href="">Dashboard</a></li>
                        <li class="active">Offer</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    {{ Form::open(['url' => route('offer.store'), 'method' => 'post', 'class' => 'container-fluid']) }}
    <!-- <div class="card mb-5 mt-5">
        <h3 class="card-title">Add New Offer</h3>
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col-sm-3"><label>Name</label></div>
                    <div class="col-sm-9">
                        <div class="form-group">
                            {{ Form::text('name', null, ['placeholder' => 'Enter Name', 'class' => 'form-control', 'required' => 'required']) }}
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-3">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary form-control">Save</button>
                </div>
            </div>
        </div>
    </div> -->
    {{ Form::close() }}
        
    <!--<form method="post">-->
        
        <div class="container-fluid">
            <div class="card mb-5 mt-5">
                <h3 class="card-title">
                    <div class="mr-auto">View Offers</div>
                    <!-- <a href="" class="ml-auto text-white" title="Remove Selected" data-toggle="tooltip">
                        <i class="icon-trash-o"></i>
                    </a> -->
                </h3>
                <section class="add-block">
                    <div>
                        <div class="basic-info-two">
                            @if (\Session::has('success'))
                                <div class="alert alert-success">
                                    {!! \Session::get('success') !!}</li>
                                </div>

                                @endif
                                @if(!$offers->isEmpty())
                                {{ $offers->appends($_GET)->links() }}
                                <table class="table table-bordered table-hover table-header-fix">
                                    <thead>
                                    <tr>
                                        <!-- <th></th> -->
                                        <th style="width: 80px;">Sr. No.</th>
                                        <th>Buyer Name</th>
                                        <th>Refered By</th>
                                        <th>Date</th>
                                        <th></th>
                                        <!-- <th>Actions</th> -->
                                    </tr>
                                    </thead>

                                    <tbody>
                                    @php $sn = $offers->firstItem(); @endphp
                                    @foreach($offers as $rec)
                                        <tr>
                                            <!-- <td>
                                                <label class="animated-checkbox">
                                                    <input type="checkbox" name="check[]" value="{{ $rec->product_id  }}" class="check">
                                                    <span class="label-text"></span>
                                                </label>
                                            </td> -->
                                            <td>{{ $sn++ }}.</td>
                                            <td>{{ $rec->buyer_name }}</td>
                                            <td>{{ $rec->refered_by }}</td>
                                            <td>{{ date('d M Y',  strtotime($rec->created_at)) }}</td>
                                            <td>
                                                <a href="{{ route('offer.show', $rec->id) }}">View Products</a><br>
                                                <a href="{{ route('offer.print', $rec->id) }}" target="_blank">Print</a>
                                            </td>
                                            <!-- <td>
                                                <div class="dropdown dropleft">
                                                    <button class="btn btn-link" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="icon-ellipsis-v"></i>
                                                    </button>
                                                    {{ Form::open(['url' => route('offer.destroy', [$rec->id]), 'method' => 'delete', 'id' => 'deleteForm']) }}
                                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                            <a class="dropdown-item" href="{{ route('offer.edit', [$rec->id]) }}">
                                                                <i class="icon-pencil"></i> Edit
                                                            </a>
                                                            <button type="submit" class="dropdown-item"><i class="icon-trash"></i> Delete</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </td> -->
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            {{ $offers->appends($_GET)->links() }}
                            @else
                            <div class="no_records_found">
                            No records found yet.
                            </div>
                            @endif
                        </div>
                </section>
            </div>
        </div>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script>
            $(function () {
                $(document).on('submit', '#deleteForm', function (e) {
                    if(!confirm("Are you sure to delete this record?")) {
                        e.preventDefault();
                    }
                });
            });
        </script>
@endsection

resources/views/frontend/inc/offer/print.blade.php
@foreach($offer->offer_products as $record)
	@include('frontend.inc.product-print_2', compact('offer', 'record'))
@endforeach

resources/views/frontend/inc/offer/show.blade.php
@extends('frontend.layouts.app')

@section('main_section')
    <section class="page-header mb-3">
        <div class="container-fluid">
            <div class="float-right">
                <a href="{{ route('offer.create') }}" class="btn btn-default"> <i class="icon-plus"></i> Add Offer</a>
            </div>
            <div class="clearfix">
                <div>
                    <h1>Offer</h1>
                    <ul class="breadcrumbs clearfix">
                        <li><a href="">Dashboard</a></li>
                        <li class="active">Offer</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    {{ Form::open(['url' => route('offer.store'), 'method' => 'post', 'class' => 'container-fluid']) }}
    <!-- <div class="card mb-5 mt-5">
            <h3 class="card-title">Add New Offer</h3>
            <div class="row">
                <div class="col">
                    <div class="row">
                        <div class="col-sm-3"><label>Name</label></div>
                        <div class="col-sm-9">
                            <div class="form-group">
                                {{ Form::text('name', null, ['placeholder' => 'Enter Name', 'class' => 'form-control', 'required' => 'required']) }}
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-3">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary form-control">Save</button>
                    </div>
                </div>
            </div>
        </div> -->
    {{ Form::close() }}

    <!--<form method="post">-->

    <div class="container-fluid">
        <div class="card mt-5">
            <h3 class="card-title">
                <div class="mr-auto">Offer Details</div>
            </h3>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <tr>
                            <th>Offer Number</th>
                            <td>{{ sprintf('%06d', $offer->id) }}</td>
                        </tr>
                        <tr>
                            <th>Buyer Name</th>
                            <td>{{ $offer->buyer_name }}</td>
                        </tr>
                        <tr>
                            <th>Refered By</th>
                            <td>{{ $offer->refered_by }}</td>
                        </tr>
                        <tr>
                            <th>Production Lead Time</th>
                            <td>{{ $offer->lead_time }}</td>
                        </tr>
                        <tr>
                            <th>Offer Price Terms</th>
                            <td>{{ $offer->terms }}</td>
                        </tr>
                        <tr>
                            <th>Remarks</th>
                            <td>{{ $offer->remarks }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="card mb-5">
            <h3 class="card-title">
                <div class="mr-auto">Products</div>
                <!-- <a href="" class="ml-auto text-white" title="Remove Selected" data-toggle="tooltip">
                            <i class="icon-trash-o"></i>
                        </a> -->
            </h3>
            <section class="add-block">
                <div>
                    <div class="basic-info-two">
                        @if (\Session::has('success'))
                            <div class="alert alert-success">
                                {!! \Session::get('success') !!}</li>
                            </div>
                        @endif
                        @if (!$offer->offer_products->isEmpty())
                            <table class="table table-bordered table-hover table-header-fix">
                                <thead>
                                    <tr>
                                        <!-- <th></th> -->
                                        <th style="width: 80px;">Sr. No.</th>
                                        <th colspan="2">Item Description</th>
                                        <th>Code</th>
                                        <th>MRP</th>
                                        <th>Margin</th>
                                        <th>Offer Price</th>
                                        <!-- <th>Qty</th>
                                            <th>Subtotal</th> -->
                                        <th>MOQ</th>
                                        <th>Remarks</th>
                                        <!-- <th>Actions</th> -->
                                    </tr>
                                </thead>

                                <tbody>
                                    @php $sn = 1; @endphp
                                    @foreach ($offer->offer_products as $rec)
                                        <tr>
                                            <!-- <td>
                                                    <label class="animated-checkbox">
                                                        <input type="checkbox" name="check[]" value="{{ $rec->product_id }}" class="check">
                                                        <span class="label-text"></span>
                                                    </label>
                                                </td> -->
                                            <td>{{ $sn++ }}.</td>
                                            <td style="width: 50px;">
                                                <img src="{{ url('imgs/products/' . $rec->product_image) }}"
                                                    alt="${row.product_name}" class="image-thumb">
                                            </td>
                                            <td>{{ $rec->product_name }}</td>
                                            <td>{{ $rec->product_code }}</td>
                                            <td>{{ $rec->product_mrp }}</td>
                                            <td>{{ $rec->pivot->margin }}%</td>
                                            <td>{{ $rec->pivot->price }}</td>
                                            <!--  <td>{{ $rec->pivot->qty }}</td>
                                                <td>{{ $rec->pivot->price * $rec->pivot->qty }}</td> -->
                                            <td>{{ $rec->pivot->moq }}</td>
                                            <td>{{ $rec->pivot->remarks }}</td>
                                            <!-- <td>
                                                    <div class="dropdown dropleft">
                                                        <button class="btn btn-link" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            <i class="icon-ellipsis-v"></i>
                                                        </button>
                                                        {{ Form::open(['url' => route('offer.destroy', [$rec->id]), 'method' => 'delete', 'id' => 'deleteForm']) }}
                                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                                <a class="dropdown-item" href="{{ route('offer.edit', [$rec->id]) }}">
                                                                    <i class="icon-pencil"></i> Edit
                                                                </a>
                                                                <button type="submit" class="dropdown-item"><i class="icon-trash"></i> Delete</button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </td> -->
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                    </div>
                @else
                    <div class="no_records_found">
                        No records found yet.
                    </div>
                    @endif
                </div>
            </section>
        </div>
    </div>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        $(function() {
            $(document).on('submit', '#deleteForm', function(e) {
                if (!confirm("Are you sure to delete this record?")) {
                    e.preventDefault();
                }
            });
        });
    </script>
@endsection